settings:
  legacy:
    force: false
    interval: 0s
server:
    status: true
    open: false
    host: localhost
    port: 8080 
schema:
- name: olein
  path: D:\riset\go\olein
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
